// This will only be ussed by the system as a default fallback measure.
import { IMaterial, IMaterialTemplate } from "../types";

export const availableMaterials: Partial<IMaterialTemplate>[] = [
	{
		id: "1",
		name: "Steel Rebar",
		units: ["tons", "kg"],
		defaultUnit: "tons",
		unitCost: 500,
	},
	{
		id: "2",
		name: "Concrete Mix",
		units: ["cubic yards", "cubic meters"],
		defaultUnit: "cubic yards",
		unitCost: 120,
	},
	{
		id: "3",
		name: "Lumber 2x4",
		units: ["pieces", "feet"],
		defaultUnit: "pieces",
		unitCost: 8,
	},
	{
		id: "4",
		name: "Electrical Wire",
		units: ["feet", "meters"],
		defaultUnit: "feet",
		unitCost: 2.5,
	},
	{
		id: "5",
		name: "PVC Pipe",
		units: ["feet", "meters"],
		defaultUnit: "feet",
		unitCost: 3,
	},
	{
		id: "6",
		name: "Drywall Sheets",
		units: ["pieces"],
		defaultUnit: "pieces",
		unitCost: 15,
	},
	{
		id: "7",
		name: "Insulation",
		units: ["rolls"],
		defaultUnit: "rolls",
		unitCost: 45,
	},
	{
		id: "8",
		name: "Roofing Shingles",
		units: ["bundles"],
		defaultUnit: "bundles",
		unitCost: 85,
	},
	{
		id: "9",
		name: "Cement",
		units: ["bags"],
		defaultUnit: "bags",
		unitCost: 12,
	},
	{
		id: "10",
		name: "Paint",
		units: ["gallons", "liters"],
		defaultUnit: "gallons",
		unitCost: 35,
	},
	{
		id: "11",
		name: "Tiles",
		units: ["square feet", "square meters"],
		defaultUnit: "square feet",
		unitCost: 4.5,
	},
	{
		id: "12",
		name: "Windows",
		units: ["pieces"],
		defaultUnit: "pieces",
		unitCost: 250,
	},
	{
		id: "13",
		name: "Doors",
		units: ["pieces"],
		defaultUnit: "pieces",
		unitCost: 180,
	},
	{
		id: "14",
		name: "HVAC Units",
		units: ["pieces"],
		defaultUnit: "pieces",
		unitCost: 1200,
	},
	{
		id: "15",
		name: "Plumbing Fixtures",
		units: ["pieces"],
		defaultUnit: "pieces",
		unitCost: 150,
	},
];
